require "good_news/version"
require "open-uri"
require "nokogiri"
require "pry"
require_relative "../lib/good_news/cli"
require_relative "../lib/good_news/article"
require_relative "../lib/good_news/scraper"
#require_relative "../lib/good_news/version"